# Generated by Django 4.2 on 2023-07-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogiist',
            fields=[
                ('Blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('Author_name', models.CharField(max_length=200)),
                ('Publish_date', models.DateTimeField()),
                ('Blog_cateogry', models.CharField(blank=True, max_length=300, null=True)),
                ('Blog_title', models.CharField(max_length=400)),
                ('Blog_caption', models.CharField(max_length=500)),
                ('Blog_img', models.ImageField(blank=True, null=True, upload_to='blogs')),
            ],
        ),
    ]
