# Generated by Django 4.2 on 2023-07-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogiist',
            new_name='Bloglist',
        ),
    ]
